version: "3"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db postgres
    db:
        image: postgres:15
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
            POSTGRES_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

    # pgAdmin
    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        depends_on:
            - db
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
